# Generated by Django 5.2.4 on 2025-10-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_alter_application_applicant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='internships/pdfs/'),
        ),
    ]
