# Generated by Django 5.2.4 on 2025-09-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('job_seeker', 'Job Seeker'), ('employer', 'Employer'), ('researcher', 'Researcher'), ('intern', 'Intern')], max_length=20),
        ),
    ]
