# Generated by Django 5.2.4 on 2025-10-03 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research_paper', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
